name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-jruby
      min_version: 2.3

  host:
    needs: ruby-versions
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - macos-13
        - macos-14
        - windows-latest
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        include:
        - { os: windows-latest , ruby: mswin     } # ruby/ruby windows CI
        - { os: ubuntu-latest  , ruby: jruby-9.3 } # Ruby 2.7
        - { os: ubuntu-latest  , ruby: jruby-9.4 } # Ruby 3.1
        - { os: macos-latest   , ruby: truffleruby-head }
        - { os: ubuntu-latest  , ruby: truffleruby-head }
        exclude:
        - { os: macos-14, ruby: 2.3 }
        - { os: macos-14, ruby: 2.4 }
        - { os: macos-14, ruby: 2.5 }
        - { os: windows-latest, ruby: jruby }
        - { os: windows-latest, ruby: jruby-head }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel
          # only needed for Ruby 2.3
          mingw: ragel

      - run: |
          bundle config --without benchmark
          bundle install

      - run: rake compile

      - run: rake test

      - run: rake build

      - run: gem install pkg/*.gem
        if: ${{ matrix.ruby != '3.2' }}
