name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-jruby
      min_version: 2.7

  host:
    needs: ruby-versions
    name: ${{ matrix.os }} ${{ matrix.ruby }} ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        env:
          - ""
        include:
          - { os: ubuntu-24.04-arm, ruby: 3.4 }
          - { os: ubuntu-latest  , ruby: 3.4, env: "JSON_DISABLE_SIMD=1" }
          - { os: macos-13, ruby: 3.4 }
          - { os: windows-latest , ruby: mswin     } # ruby/ruby windows CI
          - { os: ubuntu-latest  , ruby: jruby-9.4 } # Ruby 3.1
          - { os: macos-latest   , ruby: truffleruby-head }
          - { os: ubuntu-latest  , ruby: truffleruby-head }
        exclude:
          - { os: windows-latest, ruby: jruby }
          - { os: windows-latest, ruby: jruby-head }

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: "${{ startsWith(matrix.ruby, 'jruby') && 'ragel' || '' }}"
          brew: "${{ startsWith(matrix.ruby, 'jruby') && 'ragel' || '' }}"

      - run: |
          bundle config --without benchmark
          bundle install

      - run: rake compile ${{ matrix.env }}

      - run: rake test JSON_COMPACT=1 ${{ matrix.env }}

      - run: rake build

      - run: gem install pkg/*.gem
        if: ${{ matrix.ruby != '3.2' }}

  valgrind:
    name: Ruby memcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: "3.3"
          apt-get: valgrind

      - run: |
          bundle config --without benchmark
          bundle install

      - run: rake compile

      - run: rake valgrind JSON_COMPACT=1
